Print the log if configure fails

diff --git a/scripts/automator/build/os-defaults b/scripts/automator/build/os-defaults
--- a/scripts/automator/build/os-defaults
+++ b/scripts/automator/build/os-defaults
@@ -29,9 +29,11 @@ function autogen() {
 function configure() {
 	if [[ ! -f Makefile || ! -f .previous_build || configure -nt Makefile ]]; then
 		export CXXFLAGS="${CFLAGS} ${CXXONLY}"
-		set -x
-		./configure --enable-core-inline ${configure_additions[*]}
-		set +x
+		if ! ./configure --enable-core-inline ${configure_additions[*]}; then
+			echo "Failed to configure.. dumping the log:"
+			cat config.log
+			exit 1
+		fi
 	fi
 }
 
