Remove hard-coded version string from MSVC CI

diff --git a/.github/workflows/windows-msvc.yml b/.github/workflows/windows-msvc.yml
--- a/.github/workflows/windows-msvc.yml
+++ b/.github/workflows/windows-msvc.yml
@@ -178,10 +178,19 @@ jobs:
         run: |
           # Construct VC_REDIST_DIR
           readonly VC_REDIST_BASE="C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Redist/MSVC"
-          readonly VC_REDIST_VERSION="14.38.33135"
           readonly VC_REDIST_CRT_VERSION="Microsoft.VC143.CRT"
-          export VC_REDIST_DIR="$VC_REDIST_BASE/$VC_REDIST_VERSION/${{ matrix.conf.arch }}/$VC_REDIST_CRT_VERSION"
-          find "$VC_REDIST_BASE" -maxdepth 3 -type d
+          for ENTRY in "$VC_REDIST_BASE"/*
+          do
+              ENTRY=$ENTRY/${{ matrix.conf.arch }}/$VC_REDIST_CRT_VERSION
+              if [ -d "$ENTRY" ]; then
+                  export VC_REDIST_DIR=$ENTRY
+                  break
+              fi
+          done
+          if [ ! -d "$VC_REDIST_DIR" ]; then
+              echo "Failed to find MSVC Redistributable"
+              exit 1
+          fi
 
           # Package
           ./scripts/create-package.sh \
